namespace ADA.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ModificationDuDomainPOurGestionDesClesEtrangereNonNullable : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.ArticleRevue", "RevueId", "dbo.Revue");
            DropForeignKey("dbo.RevueGroupeIndex", "GroupeIndexId", "dbo.GroupeIndex");
            DropForeignKey("dbo.Index", "GroupeIndexId", "dbo.GroupeIndex");
            DropForeignKey("dbo.FonctionLieu", "FonctionId", "dbo.Fonction");
            DropForeignKey("dbo.FonctionLieu", "LieuId", "dbo.Lieu");
            DropForeignKey("dbo.Lieu", "TypeLieuId", "dbo.TypeLieu");
            DropForeignKey("dbo.FonctionTypeLieu", "FonctionId", "dbo.Fonction");
            DropForeignKey("dbo.FonctionTypeLieu", "TypeLieuId", "dbo.TypeLieu");
            DropForeignKey("dbo.PretreFonctionLieu", "LieuId", "dbo.Lieu");
            DropForeignKey("dbo.PretreArticleRevue", "PretreId", "dbo.Pretre");
            DropForeignKey("dbo.PretreDocument", "PretreId", "dbo.Pretre");
            DropForeignKey("dbo.PretreFonctionLieu", "PretreId", "dbo.Pretre");
            DropForeignKey("dbo.PretrePhoto", "PretreId", "dbo.Pretre");
            DropForeignKey("dbo.PretreArticleRevue", "RevueId", "dbo.Revue");
            DropForeignKey("dbo.RevueGroupeIndex", "RevueId", "dbo.Revue");
            DropIndex("dbo.ArticleRevue", new[] { "RevueId" });
            DropIndex("dbo.Index", new[] { "GroupeIndexId" });
            DropIndex("dbo.RevueGroupeIndex", new[] { "GroupeIndexId" });
            DropIndex("dbo.RevueGroupeIndex", new[] { "RevueId" });
            DropIndex("dbo.FonctionLieu", new[] { "FonctionId" });
            DropIndex("dbo.FonctionLieu", new[] { "LieuId" });
            DropIndex("dbo.Lieu", new[] { "TypeLieuId" });
            DropIndex("dbo.FonctionTypeLieu", new[] { "FonctionId" });
            DropIndex("dbo.FonctionTypeLieu", new[] { "TypeLieuId" });
            DropIndex("dbo.PretreFonctionLieu", new[] { "PretreId" });
            DropIndex("dbo.PretreFonctionLieu", new[] { "LieuId" });
            DropIndex("dbo.PretreArticleRevue", new[] { "RevueId" });
            DropIndex("dbo.PretreArticleRevue", new[] { "PretreId" });
            DropIndex("dbo.PretreDocument", new[] { "PretreId" });
            DropIndex("dbo.PretrePhoto", new[] { "PretreId" });
            AlterColumn("dbo.ArticleRevue", "RevueId", c => c.Int(nullable: false));
            AlterColumn("dbo.Index", "GroupeIndexId", c => c.Int(nullable: false));
            AlterColumn("dbo.RevueGroupeIndex", "GroupeIndexId", c => c.Int(nullable: false));
            AlterColumn("dbo.RevueGroupeIndex", "RevueId", c => c.Int(nullable: false));
            AlterColumn("dbo.FonctionLieu", "FonctionId", c => c.Int(nullable: false));
            AlterColumn("dbo.FonctionLieu", "LieuId", c => c.Int(nullable: false));
            AlterColumn("dbo.Lieu", "TypeLieuId", c => c.Int(nullable: false));
            AlterColumn("dbo.FonctionTypeLieu", "FonctionId", c => c.Int(nullable: false));
            AlterColumn("dbo.FonctionTypeLieu", "TypeLieuId", c => c.Int(nullable: false));
            AlterColumn("dbo.PretreFonctionLieu", "PretreId", c => c.Int(nullable: false));
            AlterColumn("dbo.PretreFonctionLieu", "LieuId", c => c.Int(nullable: false));
            AlterColumn("dbo.PretreArticleRevue", "RevueId", c => c.Int(nullable: false));
            AlterColumn("dbo.PretreArticleRevue", "PretreId", c => c.Int(nullable: false));
            AlterColumn("dbo.PretreDocument", "PretreId", c => c.Int(nullable: false));
            AlterColumn("dbo.PretrePhoto", "PretreId", c => c.Int(nullable: false));
            CreateIndex("dbo.ArticleRevue", "RevueId");
            CreateIndex("dbo.Index", "GroupeIndexId");
            CreateIndex("dbo.RevueGroupeIndex", "GroupeIndexId");
            CreateIndex("dbo.RevueGroupeIndex", "RevueId");
            CreateIndex("dbo.FonctionLieu", "FonctionId");
            CreateIndex("dbo.FonctionLieu", "LieuId");
            CreateIndex("dbo.Lieu", "TypeLieuId");
            CreateIndex("dbo.FonctionTypeLieu", "FonctionId");
            CreateIndex("dbo.FonctionTypeLieu", "TypeLieuId");
            CreateIndex("dbo.PretreFonctionLieu", "LieuId");
            CreateIndex("dbo.PretreFonctionLieu", "PretreId");
            CreateIndex("dbo.PretreArticleRevue", "RevueId");
            CreateIndex("dbo.PretreArticleRevue", "PretreId");
            CreateIndex("dbo.PretreDocument", "PretreId");
            CreateIndex("dbo.PretrePhoto", "PretreId");
            AddForeignKey("dbo.ArticleRevue", "RevueId", "dbo.Revue", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RevueGroupeIndex", "GroupeIndexId", "dbo.GroupeIndex", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Index", "GroupeIndexId", "dbo.GroupeIndex", "Id", cascadeDelete: true);
            AddForeignKey("dbo.FonctionLieu", "FonctionId", "dbo.Fonction", "Id", cascadeDelete: true);
            AddForeignKey("dbo.FonctionLieu", "LieuId", "dbo.Lieu", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Lieu", "TypeLieuId", "dbo.TypeLieu", "Id", cascadeDelete: true);
            AddForeignKey("dbo.FonctionTypeLieu", "FonctionId", "dbo.Fonction", "Id", cascadeDelete: true);
            AddForeignKey("dbo.FonctionTypeLieu", "TypeLieuId", "dbo.TypeLieu", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PretreFonctionLieu", "LieuId", "dbo.Lieu", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PretreArticleRevue", "PretreId", "dbo.Pretre", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PretreDocument", "PretreId", "dbo.Pretre", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PretreFonctionLieu", "PretreId", "dbo.Pretre", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PretrePhoto", "PretreId", "dbo.Pretre", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PretreArticleRevue", "RevueId", "dbo.Revue", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RevueGroupeIndex", "RevueId", "dbo.Revue", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.RevueGroupeIndex", "RevueId", "dbo.Revue");
            DropForeignKey("dbo.PretreArticleRevue", "RevueId", "dbo.Revue");
            DropForeignKey("dbo.PretrePhoto", "PretreId", "dbo.Pretre");
            DropForeignKey("dbo.PretreFonctionLieu", "PretreId", "dbo.Pretre");
            DropForeignKey("dbo.PretreDocument", "PretreId", "dbo.Pretre");
            DropForeignKey("dbo.PretreArticleRevue", "PretreId", "dbo.Pretre");
            DropForeignKey("dbo.PretreFonctionLieu", "LieuId", "dbo.Lieu");
            DropForeignKey("dbo.FonctionTypeLieu", "TypeLieuId", "dbo.TypeLieu");
            DropForeignKey("dbo.FonctionTypeLieu", "FonctionId", "dbo.Fonction");
            DropForeignKey("dbo.Lieu", "TypeLieuId", "dbo.TypeLieu");
            DropForeignKey("dbo.FonctionLieu", "LieuId", "dbo.Lieu");
            DropForeignKey("dbo.FonctionLieu", "FonctionId", "dbo.Fonction");
            DropForeignKey("dbo.Index", "GroupeIndexId", "dbo.GroupeIndex");
            DropForeignKey("dbo.RevueGroupeIndex", "GroupeIndexId", "dbo.GroupeIndex");
            DropForeignKey("dbo.ArticleRevue", "RevueId", "dbo.Revue");
            DropIndex("dbo.PretrePhoto", new[] { "PretreId" });
            DropIndex("dbo.PretreDocument", new[] { "PretreId" });
            DropIndex("dbo.PretreArticleRevue", new[] { "PretreId" });
            DropIndex("dbo.PretreArticleRevue", new[] { "RevueId" });
            DropIndex("dbo.PretreFonctionLieu", new[] { "PretreId" });
            DropIndex("dbo.PretreFonctionLieu", new[] { "LieuId" });
            DropIndex("dbo.FonctionTypeLieu", new[] { "TypeLieuId" });
            DropIndex("dbo.FonctionTypeLieu", new[] { "FonctionId" });
            DropIndex("dbo.Lieu", new[] { "TypeLieuId" });
            DropIndex("dbo.FonctionLieu", new[] { "LieuId" });
            DropIndex("dbo.FonctionLieu", new[] { "FonctionId" });
            DropIndex("dbo.RevueGroupeIndex", new[] { "RevueId" });
            DropIndex("dbo.RevueGroupeIndex", new[] { "GroupeIndexId" });
            DropIndex("dbo.Index", new[] { "GroupeIndexId" });
            DropIndex("dbo.ArticleRevue", new[] { "RevueId" });
            AlterColumn("dbo.PretrePhoto", "PretreId", c => c.Int());
            AlterColumn("dbo.PretreDocument", "PretreId", c => c.Int());
            AlterColumn("dbo.PretreArticleRevue", "PretreId", c => c.Int());
            AlterColumn("dbo.PretreArticleRevue", "RevueId", c => c.Int());
            AlterColumn("dbo.PretreFonctionLieu", "LieuId", c => c.Int());
            AlterColumn("dbo.PretreFonctionLieu", "PretreId", c => c.Int());
            AlterColumn("dbo.FonctionTypeLieu", "TypeLieuId", c => c.Int());
            AlterColumn("dbo.FonctionTypeLieu", "FonctionId", c => c.Int());
            AlterColumn("dbo.Lieu", "TypeLieuId", c => c.Int());
            AlterColumn("dbo.FonctionLieu", "LieuId", c => c.Int());
            AlterColumn("dbo.FonctionLieu", "FonctionId", c => c.Int());
            AlterColumn("dbo.RevueGroupeIndex", "RevueId", c => c.Int());
            AlterColumn("dbo.RevueGroupeIndex", "GroupeIndexId", c => c.Int());
            AlterColumn("dbo.Index", "GroupeIndexId", c => c.Int());
            AlterColumn("dbo.ArticleRevue", "RevueId", c => c.Int());
            CreateIndex("dbo.PretrePhoto", "PretreId");
            CreateIndex("dbo.PretreDocument", "PretreId");
            CreateIndex("dbo.PretreArticleRevue", "PretreId");
            CreateIndex("dbo.PretreArticleRevue", "RevueId");
            CreateIndex("dbo.PretreFonctionLieu", "LieuId");
            CreateIndex("dbo.PretreFonctionLieu", "PretreId");
            CreateIndex("dbo.FonctionTypeLieu", "TypeLieuId");
            CreateIndex("dbo.FonctionTypeLieu", "FonctionId");
            CreateIndex("dbo.Lieu", "TypeLieuId");
            CreateIndex("dbo.FonctionLieu", "LieuId");
            CreateIndex("dbo.FonctionLieu", "FonctionId");
            CreateIndex("dbo.RevueGroupeIndex", "RevueId");
            CreateIndex("dbo.RevueGroupeIndex", "GroupeIndexId");
            CreateIndex("dbo.Index", "GroupeIndexId");
            CreateIndex("dbo.ArticleRevue", "RevueId");
            AddForeignKey("dbo.RevueGroupeIndex", "RevueId", "dbo.Revue", "Id");
            AddForeignKey("dbo.PretreArticleRevue", "RevueId", "dbo.Revue", "Id");
            AddForeignKey("dbo.PretrePhoto", "PretreId", "dbo.Pretre", "Id");
            AddForeignKey("dbo.PretreFonctionLieu", "PretreId", "dbo.Pretre", "Id");
            AddForeignKey("dbo.PretreDocument", "PretreId", "dbo.Pretre", "Id");
            AddForeignKey("dbo.PretreArticleRevue", "PretreId", "dbo.Pretre", "Id");
            AddForeignKey("dbo.PretreFonctionLieu", "LieuId", "dbo.Lieu", "Id");
            AddForeignKey("dbo.FonctionTypeLieu", "TypeLieuId", "dbo.TypeLieu", "Id");
            AddForeignKey("dbo.FonctionTypeLieu", "FonctionId", "dbo.Fonction", "Id");
            AddForeignKey("dbo.Lieu", "TypeLieuId", "dbo.TypeLieu", "Id");
            AddForeignKey("dbo.FonctionLieu", "LieuId", "dbo.Lieu", "Id");
            AddForeignKey("dbo.FonctionLieu", "FonctionId", "dbo.Fonction", "Id");
            AddForeignKey("dbo.Index", "GroupeIndexId", "dbo.GroupeIndex", "Id");
            AddForeignKey("dbo.RevueGroupeIndex", "GroupeIndexId", "dbo.GroupeIndex", "Id");
            AddForeignKey("dbo.ArticleRevue", "RevueId", "dbo.Revue", "Id");
        }
    }
}
